name: 'pinterest_connectors'
version: '1.1.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'pinterest'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  pinterest_connectors:
    # Config indicated by + and applies to all files under models/microsoft/
    pinterest:
      +materialized: table

# Define variables here
vars:
  ad_group_history_identifier: ad_group_history
  ad_group_report_identifier: ad_group_report
  advertiser_history_identifier: advertiser_history
  campaign_history_identifier: campaign_history
  pin_promotion_history_identifier: pin_promotion_history
  pin_promotion_report_identifier: pin_promotion_report
